from data2 import NewQuestions

dict = {"response_code": 0, "results": [
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "Amazon acquired Twitch in August 2014 for $970 million dollars.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Entertainment: Music", "type": "multiple", "difficulty": "easy",
                                       "question": "What is not a wind instrument?", "correct_answer": "Viola",
                                       "incorrect_answers": ["Oboe", "Trombone", "Duduk"]},
    {"category": "Politics", "type": "multiple", "difficulty": "medium",
     "question": "Who was the British Prime Minister at the outbreak of the Second World War?",
     "correct_answer": "Neville Chamberlain",
     "incorrect_answers": ["Clement Attlee", "Winston Churchill", "Stanley Baldwin"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy", "question": "What does CPU stand for?",
     "correct_answer": "Central Processing Unit",
     "incorrect_answers": ["Central Process Unit", "Computer Personal Unit", "Central Processor Unit"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "What is the name of the former country that was succeeded by countries such as Serbia, Croatia and Slovenia?",
     "correct_answer": "Yugoslavia", "incorrect_answers": ["Czechoslovakia", "Abkhazia", "South Ossetia"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "What are the four corner states of the US?", "correct_answer": "Utah, Colorado, Arizona, New Mexico",
     "incorrect_answers": ["Oregon, Idaho, Nevada, Utah", "Kansas, Oklahoma, Arkansas, Louisiana",
                           "South Dakota, Minnesota, Nebraska, Iowa"]},
    {"category": "Entertainment: Board Games", "type": "multiple", "difficulty": "hard",
     "question": "What is the world&#039;s oldest board game?", "correct_answer": "Senet",
     "incorrect_answers": ["Chess", "Checkers", "Go"]},
    {"category": "History", "type": "multiple", "difficulty": "medium",
     "question": "When was the United States National Security Agency established?",
     "correct_answer": "November 4, 1952",
     "incorrect_answers": ["July 26, 1908", " July 1, 1973", " November 25, 2002"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The bikini is named after the &quot;Bikini Atoll&quot;, an island where the United States conducted tests on atomic bombs.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "multiple", "difficulty": "hard",
     "question": "What did the first moving picture depict?", "correct_answer": "A galloping horse",
     "incorrect_answers": ["A woman in a dress", "A man walking", "A crackling fire"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "When was &quot;Garry&#039;s Mod&quot; released?", "correct_answer": "December 24, 2004",
     "incorrect_answers": ["November 13, 2004", "December 13, 2004", "November 12, 2004"]},
    {"category": "Entertainment: Film", "type": "multiple", "difficulty": "easy",
     "question": "Which movie includes a giant bunny-like spirit who has magic powers including growing trees?",
     "correct_answer": "My Neighbor Totoro",
     "incorrect_answers": ["Hop", "Rise of the Guardians", "Alice in Wonderland"]},
    {"category": "Animals", "type": "multiple", "difficulty": "easy", "question": "How many legs do butterflies have?",
     "correct_answer": "6", "incorrect_answers": ["2", "4", "0"]},
    {"category": "Entertainment: Board Games", "type": "multiple", "difficulty": "medium",
     "question": "The board game, Nightmare was released in what year?", "correct_answer": "1991",
     "incorrect_answers": ["1992", "1989", "1995"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "hard",
     "question": "Which game was exclusive to Dreamcast?", "correct_answer": "Pen Pen TriIcelon",
     "incorrect_answers": ["Sylvester &amp; Tweety in Cagey Capers", "Perfect Dark", "Tetrisphere"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "In what city in the dystopia alternate future of Half-Life 2 do you first start in?",
     "correct_answer": "City 17", "incorrect_answers": ["City 18", "City 6", "City 45"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium", "question": "What is the capital of Senegal?",
     "correct_answer": "Dakar", "incorrect_answers": ["Nouakchott", "Conakry", "Monrovia"]},
    {"category": "Entertainment: Film", "type": "multiple", "difficulty": "easy",
     "question": "In the movie &quot;Cast Away&quot; the main protagonist&#039;s best friend while on the island is named",
     "correct_answer": "Wilson", "incorrect_answers": ["Carson", "Jackson", "Willy"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
     "question": "Which of these songs by artist Eminem contain the lyric &quot;Nice to meet you. Hi, my name is... I forgot my name!&quot;?",
     "correct_answer": "Rain Man", "incorrect_answers": ["Without Me", "Kim", "Square Dance"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "easy",
     "question": "The name of Junko Enoshima&#039;s imposter at the beginning of Danganronpa: Trigger Happy Havoc is?",
     "correct_answer": "Mukuro Ikusaba", "incorrect_answers": ["Ryota Mitarai", "Ultimate Imposter", "Komaru Naegi"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "What is the full name of the protagonist from the SNES game Clock Tower?",
     "correct_answer": "Jennifer Simpson",
     "incorrect_answers": ["Jennifer Barrows", "Jennifer Cartwright", "Jennifer Maxwell"]},
    {"category": "Entertainment: Comics", "type": "boolean", "difficulty": "easy",
     "question": "The &quot;Pepe&quot; meme originated from a comic drawn by Matt Furie called &quot;Boy&#039;s Club&quot;?",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "multiple", "difficulty": "medium",
     "question": "What stage of development do the majority of eukaryotic cells remain in for most of their life?",
     "correct_answer": "Interphase", "incorrect_answers": ["Prophase", "Stasis", "Telophase"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "easy",
     "question": "From which country did the song &quot;Gangnam Style&quot; originate from?",
     "correct_answer": "South Korea", "incorrect_answers": ["Japan", "North Korea", "China"]},
    {"category": "Celebrities", "type": "multiple", "difficulty": "medium",
     "question": "If he was still alive, in what year would Elvis Presley celebrate his 100th birthday?",
     "correct_answer": "2035", "incorrect_answers": ["2030", "2040", "2045"]},
    {"category": "History", "type": "multiple", "difficulty": "medium",
     "question": "What was Genghis Khan&#039;s real name?", "correct_answer": "Tem&uuml;jin",
     "incorrect_answers": ["M&ouml;ngke", "&Ouml;gedei", "Tem&uuml;r"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "Which of the following games in the Anno series introduced the &quot;Eco Balance&quot; gameplay mechanic?",
     "correct_answer": "Anno 2070", "incorrect_answers": ["Anno 1404", "Anno 2205", " Anno 1701"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "hard",
     "question": "In the game Danganronpa: Happy Trigger Havoc, the character Aoi Asahina&#039;s ultimate ability is what?",
     "correct_answer": "Ultimate Swimmer",
     "incorrect_answers": ["Ultimate Detective", "Ultimate Gambler", "Ultimate Dancer"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "When was Nintendo&#039;s Virtual Boy released?", "correct_answer": "1995",
     "incorrect_answers": ["1989", "1997", "1992"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "easy",
     "question": "What was Daft Punk&#039;s first studio album?", "correct_answer": "Homework",
     "incorrect_answers": ["Discovery", "Random Access Memories", "Human After All"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "Ellen McLain, the voice of GLaDOS in the Portal game series, is married to the voice actor for which Team Fortress 2 character?",
     "correct_answer": "Sniper", "incorrect_answers": ["Heavy", "Soldier", "Scout"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
     "question": "How many copies have Metallica album &quot;Metallica&quot; (A.K.A The Black Album) sold worldwide (in Millions of Copies)?",
     "correct_answer": "20.5", "incorrect_answers": ["19.5", "22.5", "25.5"]},
    {"category": "Science: Gadgets", "type": "multiple", "difficulty": "easy",
     "question": "When was the iPhone released?", "correct_answer": "2007",
     "incorrect_answers": ["2005", "2006", "2004"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "Which of these stages is not playable in &quot;Super Smash Bros. for Wii U&quot;?",
     "correct_answer": "Fountain of Dreams", "incorrect_answers": ["Bridge of Eldin", "75m", "Miiverse"]},
    {"category": "History", "type": "multiple", "difficulty": "easy", "question": "What year did World War I begin?",
     "correct_answer": "1914", "incorrect_answers": ["1905", "1919", "1925"]},
    {"category": "Politics", "type": "multiple", "difficulty": "medium",
     "question": "Who became Prime Minister of the United Kingdom in July 2016?", "correct_answer": "Theresa May",
     "incorrect_answers": ["Boris Johnson", "David Cameron", "Tony Blair"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "What is the name of the game developer who created &quot;Call Of Duty: Zombies&quot;?",
     "correct_answer": "Treyarch", "incorrect_answers": ["Sledgehammer Games", "Infinity Ward", "Naughty Dog"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "What is the name of Joel&#039;s daughter in the game, &quot;The Last of Us&quot;? ",
     "correct_answer": "Sarah", "incorrect_answers": ["Ellie", "Tess", "Marlene"]},
    {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
     "question": "What character in the Winnie the Pooh films was added by Disney and does not appear in the original books?",
     "correct_answer": "Gopher", "incorrect_answers": ["Tigger", "Heffalumps", "Rabbit"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "hard",
     "question": "Which of the following games was NOT included in Valve&#039;s Orange Box?",
     "correct_answer": "Counter-Strike",
     "incorrect_answers": ["Portal", "Half-Life 2: Episode Two", "Team Fortress 2"]},
    {"category": "Science & Nature", "type": "multiple", "difficulty": "hard",
     "question": "Coulrophobia is the irrational fear of what?", "correct_answer": "Clowns",
     "incorrect_answers": ["Cemeteries", "Needles", "Tunnels"]},
    {"category": "Sports", "type": "multiple", "difficulty": "easy",
     "question": "When was the first official international game played?", "correct_answer": "1872",
     "incorrect_answers": ["1880", "1863", "1865"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "Which country has the most Trappist breweries?", "correct_answer": "Belgium",
     "incorrect_answers": ["Netherlands", "France", "USA"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "Which American manufactured submachine gun was informally known by the American soldiers that used it as &quot;Grease Gun&quot;?",
     "correct_answer": "M3", "incorrect_answers": ["Colt 9mm", "Thompson", "MAC-10"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Vietnam&#039;s national flag is a red star in front of a yellow background.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
     "question": "The character Plum from &quot;No Game No Life&quot; is a girl.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "In the MMO RPG &quot;Realm of the Mad God&quot;, what class is known for having the highest possible defense?",
     "correct_answer": "The Knight", "incorrect_answers": ["The Wizard", "The Archer", "The Warrior"]},
    {"category": "Science & Nature", "type": "multiple", "difficulty": "medium",
     "question": "Where did the Great Storm of 1987 make landfall at, first?", "correct_answer": "Cornwall",
     "incorrect_answers": ["Surrey", "Wales", "The Midlands"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "Which of the following is not the host of a program on NPR?", "correct_answer": "Ben Shapiro",
     "incorrect_answers": ["Terry Gross", "Ira Glass", "Peter Sagal"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "In &quot;Resident Evil 3&quot;, how many inventory slots does Jill have at the start of the game?",
     "correct_answer": "10", "incorrect_answers": ["6", "8", "12"]}]}
new = NewQuestions(dict)
new.generate_new_questions()
question_data = new.output
